general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn screen on after waking up
}

# Lock screen after 5 minutes
listener {
    timeout = 300                               
    on-timeout = loginctl lock-session          
}

# Turn off laptop screen after 5.5 minutes
listener {
    timeout = 330                               
    on-timeout = hyprctl dispatch dpms off      
    on-resume = hyprctl dispatch dpms on        
}

# Suspend (Sleep) the laptop after 30 minutes
listener {
    timeout = 1800                              
    on-timeout = systemctl suspend              
}
