preload = /home/jrp/arch-hyprland-setup/wallpaper2.jpg

# Explicitly target both laptop and external home monitor
wallpaper = HDMI-A-1,/home/jrp/arch-hyprland-setup/wallpaper2.jpg
wallpaper = eDP-1,/home/jrp/arch-hyprland-setup/wallpaper2.jpg

splash = false
ipc = off
