"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

# Define the order of the prompt
# This puts the brackets and info exactly where you want them
# Layout: [user@host directory]:
format = '$username$hostname $directory$character'

[username]
show_always = true
format = "[$user](blue)"

[hostname]
ssh_only = false
format = "[@$hostname](blue)"

[directory]
format = "[$path](yellow)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[:](white) "
error_symbol = "[:](red) "

# [character]
# success_symbol = "[❯](purple)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
